### ISSUE TITLE
401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by johnthomas00** [tchellomello/python-ring-doorbell#146] opened 2019-12-23 22:49 UTC
Just started getting errors.  They may be trying to bad us from the API, but not sure.  Anyone else getting this error?

```
  File "./ring.py", line 9, in <module>
    myring = Ring('redacted', 'alsoRedacted')
  File "/home/user00/virtual/utils/lib/python3.6/site-packages/ring_doorbell/__init__.py", line 55, in __init__
    self._process_cached_session()
  File "/home/user00/virtual/utils/lib/python3.6/site-packages/ring_doorbell/__init__.py", line 81, in _process_cached_session
    req = self.query(url, raw=True)
  File "/home/user00/virtual/utils/lib/python3.6/site-packages/ring_doorbell/__init__.py", line 224, in query
    self._authenticate()
  File "/home/user00/virtual/utils/lib/python3.6/site-packages/ring_doorbell/__init__.py", line 162, in _authenticate
    req.raise_for_status()
  File "/home/user00/virtual/utils/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.ring.com/clients_api/session
```

**Comment by thanneman79** [comment] 2019-12-23 23:04
I'm getting it also. It seems to have started on the evening of 12/18. I just added some of the new stick up cams and thought that had caused it until I went back in my apps logs.

**Comment by johnthomas00** [comment] 2019-12-23 23:06
There was an update that fixed the problem from 12/18.  Make sure you are running:
ring-doorbell   0.2.5
Even with the update to ring-doorbell   0.2.5, I am getting this error.

**Comment by anomaly256** [comment] 2019-12-23 23:06
Yes this is new today.  Was working for me only a couple hours ago

**Comment by geekofweek** [comment] 2019-12-24 02:13
Just started seeing this as well.

**Comment by Jay66543** [comment] 2019-12-24 02:29
The library is using:
`User-Agent: Dalvik/2.1.0 (Linux; U; Android 9.0; SM-G850F Build"/LRX22G)` as the `user-agent`, changing it to `User-Agent: ring_official_windows/2.4.16` allows for the auth token to be grabbed.

There are also two other 2fa related headers, but adding those to the original user agent does not make for a valid token request:
```
2fa-Code: 
2fa-Support: true
```

**Comment by theplen** [comment] 2019-12-24 02:30
Same here,  0.2.5 was working until a couple of hours ago.  They must have blocked the new user-agent or some other means of detecting this library.

**Comment by geekofweek** [comment] 2019-12-24 02:52
@Jay66543 can confirm adjusting the User-Agent seems to resolve it.  Appears we are in a cat and mouse game with them locking down devices allowed to connect.  If I have some time I will see if I can scrape the official iOS User-Agent and test that.  I would assume it would be a safe bet to standardize around that one.

**Comment by geekofweek** [comment] 2019-12-24 03:03
`User-Agent: ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0` Also works, that is what the current iOS app officially uses.

**Comment by tekmaven** [comment] 2019-12-24 04:03
I confirm this is working for me.  This is how I'm hacking around it for now in HA, by editing `/components/ring/__init__.py`:

```python
from ring_doorbell.const import (HEADERS)
HEADERS["User-Agent"] = "ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0"
```

**Comment by jaraeez** [comment] 2019-12-24 04:59
> I confirm this is working for me. This is how I'm hacking around it for now in HA, by editing `/components/ring/__init__.py`:
> 
> ```python
> from ring_doorbell.const import (HEADERS)
> HEADERS["User-Agent"] = "ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0"
> ```

Cheers, that worked for me

**Comment by skynet01** [comment] 2019-12-24 05:41
> > I confirm this is working for me. This is how I'm hacking around it for now in HA, by editing `/components/ring/__init__.py`:
> > ```python
> > from ring_doorbell.const import (HEADERS)
> > HEADERS["User-Agent"] = "ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0"
> > ```
> 
> Cheers, that worked for me

I assume you just need to add that at the top of the file?

**Comment by jaraeez** [comment] 2019-12-24 06:03
> > > I confirm this is working for me. This is how I'm hacking around it for now in HA, by editing `/components/ring/__init__.py`:
> > > ```python
> > > from ring_doorbell.const import (HEADERS)
> > > HEADERS["User-Agent"] = "ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0"
> > > ```
> > 
> > 
> > Cheers, that worked for me
> 
> I assume you just need to add that at the top of the file?

Added it after line 13 like so (line 15,16)

> from ring_doorbell.utils import _exists_cache, _save_cache, _read_cache
> 
> from ring_doorbell.const import (HEADERS)
> HEADERS["User-Agent"] = "ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0"
> 
> from ring_doorbell.const import (
>     API_VERSION, API_URI, CACHE_ATTRS, CACHE_FILE,
>     DEVICES_ENDPOINT, HEADERS, NEW_SESSION_ENDPOINT, MSG_GENERIC_FAIL,
>     POST_DATA, PERSIST_TOKEN_ENDPOINT, PERSIST_TOKEN_DATA, RETRY_TOKEN,
>     OAUTH_ENDPOINT, OAUTH_DATA)

**Comment by tchellomello** [comment] 2019-12-24 06:07
> I confirm this is working for me. This is how I'm hacking around it for now in HA, by editing `/components/ring/__init__.py`:
> 
> ```python
> from ring_doorbell.const import (HEADERS)
> HEADERS["User-Agent"] = "ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0"
> ```

It's interesting how they are changing their API but I'm happy that our community is picking this very quickly.  @tekmaven  (_or someone else_)  want to submit a PR so we can get it fixed in Home Assistant?

**Comment by balloob** [comment] 2019-12-24 08:49
I have been talking to the CTO of Ring. I posted my update here: https://github.com/tchellomello/python-ring-doorbell/issues/144#issuecomment-568696354

The summary: this lib needs to follow OAuth2 spec or else they will keep blocking us.

**Comment by Lee-Fixter** [comment] 2019-12-24 09:33
Note working for me, modified .py below

```
"""Support for Ring Doorbell/Chimes."""
from datetime import timedelta
import logging

from requests.exceptions import ConnectTimeout, HTTPError
from ring_doorbell import Ring
import voluptuous as vol

from homeassistant.const import CONF_PASSWORD, CONF_SCAN_INTERVAL, CONF_USERNAME
import homeassistant.helpers.config_validation as cv
from homeassistant.helpers.dispatcher import dispatcher_send
from homeassistant.helpers.event import track_time_interval
from ring_doorbell.const import (HEADERS)
HEADERS["User-Agent"] = "ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0"
_LOGGER = logging.getLogger(__name__)

ATTRIBUTION = "Data provided by Ring.com"

NOTIFICATION_ID = "ring_notification"
NOTIFICATION_TITLE = "Ring Setup"

DATA_RING_DOORBELLS = "ring_doorbells"
DATA_RING_STICKUP_CAMS = "ring_stickup_cams"
DATA_RING_CHIMES = "ring_chimes"

DOMAIN = "ring"
DEFAULT_CACHEDB = ".ring_cache.pickle"
DEFAULT_ENTITY_NAMESPACE = "ring"
SIGNAL_UPDATE_RING = "ring_update"

SCAN_INTERVAL = timedelta(seconds=10)

CONFIG_SCHEMA = vol.Schema(
    {
        DOMAIN: vol.Schema(
            {
                vol.Required(CONF_USERNAME): cv.string,
                vol.Required(CONF_PASSWORD): cv.string,
                vol.Optional(CONF_SCAN_INTERVAL, default=SCAN_INTERVAL): cv.time_period,
            }
        )
    },
    extra=vol.ALLOW_EXTRA,
)


def setup(hass, config):
    """Set up the Ring component."""
    conf = config[DOMAIN]
    username = conf[CONF_USERNAME]
    password = conf[CONF_PASSWORD]
    scan_interval = conf[CONF_SCAN_INTERVAL]

    try:
        cache = hass.config.path(DEFAULT_CACHEDB)
        ring = Ring(username=username, password=password, cache_file=cache)
        if not ring.is_connected:
            return False
        hass.data[DATA_RING_CHIMES] = chimes = ring.chimes
        hass.data[DATA_RING_DOORBELLS] = doorbells = ring.doorbells
        hass.data[DATA_RING_STICKUP_CAMS] = stickup_cams = ring.stickup_cams

        ring_devices = chimes + doorbells + stickup_cams

    except (ConnectTimeout, HTTPError) as ex:
        _LOGGER.error("Unable to connect to Ring service: %s", str(ex))
        hass.components.persistent_notification.create(
            "Error: {}<br />"
            "You will need to restart hass after fixing."
            "".format(ex),
            title=NOTIFICATION_TITLE,
            notification_id=NOTIFICATION_ID,
        )
        return False

    def service_hub_refresh(service):
        hub_refresh()

    def timer_hub_refresh(event_time):
        hub_refresh()

    def hub_refresh():
        """Call ring to refresh information."""
        _LOGGER.debug("Updating Ring Hub component")

        for camera in ring_devices:
            _LOGGER.debug("Updating camera %s", camera.name)
            camera.update()

        dispatcher_send(hass, SIGNAL_UPDATE_RING)

    # register service
    hass.services.register(DOMAIN, "update", service_hub_refresh)

    # register scan interval for ring
    track_time_interval(hass, timer_hub_refresh, scan_interval)

    return True

```

**Comment by ToddNJ** [comment] 2019-12-24 12:31
this modification to adjust the request header worked for me using HASSIO 0.103.4, but i had to modify the file directly.   Cloning the folder to /config/custom_components/ring then modifying there did not work for me.

**Comment by ToddNJ** [comment] 2019-12-24 12:32
@balloob THANK YOU!   Any chance we could also use a "shared" account that has access to the main account, instead of the main account?  From the mobile app perspective, shared users see camera, motion, get alerts, etc.

**Comment by Lee-Fixter** [comment] 2019-12-24 13:15
> this modification to adjust the request header worked for me using HASSIO 0.103.4, but i had to modify the file directly. Cloning the folder to /config/custom_components/ring then modifying there did not work for me.

Where is the file located?

**Comment by Scope666** [comment] 2019-12-24 16:18
I used Portainer for my HASSIO install.  It gives you a command prompt into the homeassistant container.  From there it was:

/usr/src/homeassistant/homeassistant/components/ring

![image](https://user-images.githubusercontent.com/31927547/71419748-1d9f5d80-263f-11ea-9ce8-c8b5b15ee0d0.png)

**Comment by Lee-Fixter** [comment] 2019-12-24 19:28
> /usr/src/homeassistant/homeassistant/components/ring

Great, thanks!

**Comment by Lee-Fixter** [comment] 2019-12-24 19:44
> I used Portainer for my HASSIO install. It gives you a command prompt into the homeassistant container. From there it was:
> 
> /usr/src/homeassistant/homeassistant/components/ring
> 
> ![image](https://user-images.githubusercontent.com/31927547/71419748-1d9f5d80-263f-11ea-9ce8-c8b5b15ee0d0.png)

Once I get to that dir, how to I edit the file? nano/vim etc are not installed..

**Comment by Scope666** [comment] 2019-12-24 20:28
VI worked for me, it was already there.

**Comment by tux43** [comment] 2019-12-24 21:09
> I used Portainer for my HASSIO install. It gives you a command prompt into the homeassistant container. From there it was:
> 
> /usr/src/homeassistant/homeassistant/components/ring

Are you sure? This is a source file and does not look right.

I edited `/usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py` and it worked for me.

**Comment by Scope666** [comment] 2019-12-24 21:36
Are you sure you're on HASSIO?  That almost looks like a Virtual Environment path.

Either way as long as you got it working.     ;)

**Comment by asantaga** [comment] 2019-12-24 21:56
I can confirm tu43 , in my Docker image (official) it was also /usr/local/lib/python3.7/site-packages/ring_doorbell/__init__.py

but this is only a workaround right?

**Comment by asantaga** [comment] 2019-12-24 22:09
Also , Ive seen another thread which indicates ring are blocking us because we dont follow oauth properly (or at all).. Does anyone know if this is for the API as a whole or just within Home Assistant?

**Comment by d0ugal** [comment] 2019-12-24 22:13
> Also , Ive seen another thread which indicates ring are blocking us because we dont follow oauth properly (or at all).. Does anyone know if this is for the API as a whole or just within Home Assistant?

I don’t know, but I believe it will be the API as a whole. I don’t think they can easily tell the requests are coming from home assistant. We pretend to be the phone apps by setting the headers.

**Comment by tux43** [comment] 2019-12-24 22:58
> Are you sure you're on HASSIO? That almost looks like a Virtual Environment path.
> 
> Either way as long as you got it working. ;)

No, I am not on HASSIO and maybe that is the difference. I am using docker and edited this file within the container.

**Comment by Scope666** [comment] 2019-12-24 22:59
I followed the procedure posted above which was editing:

/components**/ring/**__init__.py  not   /**ring_doorbell**/init.py

**Comment by tux43** [comment] 2019-12-24 23:01
> I followed the procedure posted above which was editing:
> 
> `/components/ring/__init__.py not /ring_doorbell/init.py`

Are you using HASSIO or Docker or ???? Reading through the thread and my experience it is different on both (assumption by me not confirmed)

**Comment by Scope666** [comment] 2019-12-24 23:04
I'm on Hassio, installed on Ubuntu.  For me the path was /usr/src/homeassistant/homeassistant/components/ring INSIDE the home_assistant container.  The hack worked for me.

**Comment by thehaxxa** [comment] 2019-12-25 00:32
Confirming this temporary fix worked for me: 

`harrison@home-assistant:~$ sudo docker exec -it b9aa6c41174b /bin/bash`
`bash-5.0# cd /usr/local/lib/python3.7/site-packages/ring_doorbell/`
`bash-5.0# vi __init__.py`

Inserted new line below `from ring_doorbell.stickup_cam import RingStickUpCam` (_line 23_) :

![image](https://user-images.githubusercontent.com/2765052/71427200-cc0fd500-2709-11ea-9523-4053e04dc2d6.png)

All my Ring devices are now working, hopefully holds until the proper OAuth method is added to API or a new API is developed.

**Comment by xernaj** [comment] 2019-12-25 12:35
PRs have been raised.

https://github.com/tchellomello/python-ring-doorbell/pull/149

Suggest you use that one ('User-Agent': 'ring/5.21.0.5 CFNetwork/1121.2.2 Darwin/19.2.0') rather than mine? (https://github.com/tchellomello/python-ring-doorbell/pull/151). We just need a user agent that's unlikely to be blocked too quickly.

**Comment by asantaga** [comment] 2019-12-25 12:45
I think we should distinguish ring api enhancement and how it works within HA.. I've seen comments which indicate the functionality needs to be implemented within HA oauth accounts whereas I think the issue needs to be resolved within the API first and then HA accounts later..

just saying..

**Comment by tchellomello** [comment] 2019-12-26 06:56
Hello, applying the workaround proposed on #149 did help to temporarily address the issue, however, it will matter of time to get it blocked again IMHO. 

Reviewing the code this night I actually found a pretty nasty bug (_sorry about that_)  https://github.com/tchellomello/python-ring-doorbell/blob/master/ring_doorbell/__init__.py#L90-L104 which causes the code to generate a new _Bearer_ token for **every single request**. No wonder why this is getting blocked. 

I think the proper resolution will be to store the `access_token` and the `refresh_token` as an attribute and then create a mechanism or use the `oauth2` library to control and refresh the token. We could create an independent class to treat this or just embed it into the code. 

I'll try to read more about how to properly use the library. Any help is very welcome too!

**Comment by niekniek89** [comment] 2019-12-26 07:00
what are the correct commands to edit and save the __init__.py in VI mode?

**Comment by tchellomello** [comment] 2019-12-26 07:01
> what are the correct commands to edit and save the **init**.py in VI mode?

```
vi __init__.py
<MAKE THE CHANGES>
ESC ESC
:wq
```

**Comment by niekniek89** [comment] 2019-12-26 07:10
@tchellomello thanks for your quick response! with your help we have succeeded in modifying __init__.py.

**Closed** 2019-12-27 16:32 UTC
Labels: PRIORITY, bug, help wanted
