### ISSUE TITLE
Ring API stopped working

### ISSUE THREAD

**Issue by ualex73** [tchellomello/python-ring-doorbell#142] opened 2019-12-19 11:59 UTC
This morning the Home Assistant component stopped worked, with the following errors:

`2019-12-19 12:53:58 ERROR (SyncWorker_7) [homeassistant.components.ring] Unable to connect to Ring service: 403 Client Error: Forbidden for url: https://api.ring.com/clients_api/session`
`2019-12-19 12:53:58 ERROR (MainThread) [homeassistant.setup] Setup failed for ring: Integration failed to initialize.`

It started around 01:00 (CET) on the 18th of December.

**Comment by MikeJMcGuire** [comment] 2019-12-19 12:06
Have confirmed using the ring-doorbell package directly with a script is resulting in the same error as home assistant.

**Comment by ComputerSmiths** [comment] 2019-12-19 12:13
Python code gets:

Traceback (most recent call last):
  File "RingBattery.py", line 30, in <module>
    for dev in list(myring.doorbells):
  File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 271, in doorbells
    return self.__devices('doorbells')
  File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 245, in __devices
    req = self.query(url).get('doorbots')
  File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 204, in query
    self._authenticate()
  File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 154, in _authenticate
    req.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.ring.com/clients_api/session

**Comment by isabellaalstrom** [comment] 2019-12-19 12:31
Can comfirm that the oauth process and the https://api.ring.com/clients_api/ring_devices endpoint still works in Postman.

**Comment by isabellaalstrom** [comment] 2019-12-19 12:33
Can confirm that `https://api.ring.com/clients_api/ring_devices` still works through postman, so there should be a change to just the sessions endpoint maybe.

**Comment by xernaj** [comment] 2019-12-19 15:54
I've had a look at this and noticed the following changes that will be required:
- Update user agent in header as that is now blocked
- OAuth bearer token must be in calls or it will be rejected
- 429 occurs frequently as the above aren't implemented and ends up hammering their API
 
I'm working on my own branch now and so far it's working well for gets. As far as post/puts... haven't tried.

**Comment by ComputerSmiths** [comment] 2019-12-19 15:56
Also, the simplest failing code directly in the Python interpreter:
>>> from ring_doorbell import Ring
>>> myring = Ring('<email>', '<password>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 53, in __init__
    self._process_cached_session()
  File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 79, in _process_cached_session
    req = self.query(url, raw=True)
  File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 204, in query
    self._authenticate()
  File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/__init__.py", line 154, in _authenticate
    req.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.ring.com/clients_api/session

I don't know if there's a way to do OATH or 2FA in this package.

**Comment by arsaboo** [comment] 2019-12-19 15:58
@xernaj Can you create a PR against this branch so that we can get the fix fast in HA?

**Comment by xernaj** [comment] 2019-12-19 21:14
> @xernaj Can you create a PR against this branch so that we can get the fix fast in HA?

PR #143  raised. If someone could test it out in the real world too, that would be great. I can only confirm that gets for sensors are working (including camera for HA).

**Comment by ComputerSmiths** [comment] 2019-12-19 21:24
Happy to test, but not sure how.  I seem to have installed the original code with pip, if that matters...

Thanks!

**Comment by Scope666** [comment] 2019-12-19 21:27
Also happy to test, can I pull it down as a custom component?  I'm running Hassio   (or pip install maybe?)

**Comment by xernaj** [comment] 2019-12-19 22:27
In order to test with HA. You'll need to grab the HA ring component and copy to your custom_components. You'll then need to modify manifest.json (which should be I custom_components/ring) to point to the updated package branch (this would be the github zip link). The requirements format is mentioned here https://developers.home-assistant.io/docs/en/0.90.0/creating_component_deps_and_reqs.html. I'll update comment with more details later.

**Comment by mhpetiwala** [comment] 2019-12-19 23:06
I pulled the changes done by @xernaj and merged with my 0.85.1 HASS and they seem to work. The ring component was able to initialize and pull motion/ding data via the API. Don't see any errors on HASS side either except the normal warning:

Log Details (WARNING)
Thu Dec 19 2019 17:01:40 GMT-0600 (CST)

Setup of platform ring is taking over 10 seconds.

**Comment by geekofweek** [comment] 2019-12-19 23:11
Testing it out now, seems ok so far.

**Comment by Scope666** [comment] 2019-12-19 23:11
Not sure what I'm doing wrong:

```
{
  "domain": "ring",
  "name": "Ring",
  "documentation": "https://github.com/xernaj/python-ring-doorbell/archive/fix/oauth-fail-due-to-blocked-user-agent.zip",
  "requirements": [
    "ring_doorbell==0.2.3"
  ],
  "dependencies": [
    "ffmpeg"
  ],
  "codeowners": []
}

```



```
2019-12-19 18:09:21 INFO (SyncWorker_4) [homeassistant.loader] Loaded ring from custom_components.ring,
2019-12-19 18:09:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform ring.camera: Unable to set up component.,
2019-12-19 18:09:26 ERROR (MainThread) [homeassistant.setup] Setup failed for ring: Integration failed to initialize.,
2019-12-19 18:09:26 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform ring.binary_sensor: Unable to set up component.,
2019-12-19 18:09:26 INFO (MainThread) [homeassistant.setup] Setup of domain ring took 1.3 seconds.,
2019-12-19 18:09:26 ERROR (SyncWorker_21) [custom_components.ring] Unable to connect to Ring service: 403 Client Error: Forbidden for url: https://api.ring.com/clients_api/session,
2019-12-19 18:09:24 INFO (MainThread) [homeassistant.setup] Setting up ring,
2019-12-19 18:09:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ring which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```

**Comment by geekofweek** [comment] 2019-12-19 23:13
should be more like this, you've got it listed as documentation and not a requirement.

```
  "domain": "ring",
  "name": "Ring",
  "documentation": "https://www.home-assistant.io/integrations/ring",
  "requirements": [
    "https://github.com/xernaj/python-ring-doorbell/archive/fix/oauth-fail-due-to-blocked-user-agent.zip#ring_doorbell==0.2.4"
  ],
  "dependencies": [
    "ffmpeg"
  ],
  "codeowners": []
```

**Comment by Scope666** [comment] 2019-12-19 23:19
@geekofweek   Thanks so much!  I haven't messed with a manifest.json file before so the syntax was a bit confusing.

@xernaj   It's working over here... great work!

**Comment by xernaj** [comment] 2019-12-19 23:35
Thanks for testing! Haven't had time to update instructions on how to put all the pieces together but I'm glad everyone worked it out.

I think the python-ring-doorbell component can be improved further as it still seems to make too many calls to the API, particularly oauth, which could end up getting blocked later on. There's also potential to speed up the process or reduce the amount of "Setup of platform ring is taking over 10 seconds." messages in HA.

The PR should hopefully help everyone out in the mean time.

**Comment by brama1966** [comment] 2019-12-19 23:48
Yep working here as well
motion returning to clear takes for every
but that how it was before it fell over
well can't wait for the next thing to fall over

**Comment by brama1966** [comment] 2019-12-19 23:54
> In order to test with HA. You'll need to grab the HA ring component and copy to your custom_components. You'll then need to modify manifest.json (which should be located in custom_components/ring) to point to the updated package branch (this would be the github zip link). The requirements format is mentioned here https://developers.home-assistant.io/docs/en/0.90.0/creating_component_deps_and_reqs.html. I'll update comment with more details later.

Yeah i did the hack of the HA

potainer docker
homeassistant container
console
and just replaced the ring_doorbell folder in the /usr/local/lib/python3.7/site-packages
reboot 
and 
**yippee ki yay**

**Comment by jaraeez** [comment] 2019-12-20 00:05
Any directions where I'm going wrong?
Copied _cp -a /srv/homeassistant/lib/python3.6/site-packages/ring_doorbell_ to _custom_components_
Created manifest.json in the same directory & restarted home assistant - same error.

**Comment by Scope666** [comment] 2019-12-20 00:19
Here, I zipped up my working edit, it goes under custom_components

https://drive.google.com/file/d/1C41E7OlOUZLtXBHosV9U6HTlBWNN8Cxf/view?usp=sharing

**Comment by jaraeez** [comment] 2019-12-20 00:28
Thanks, unfortunately I still get the below error
`2019-12-20 10:25:40 ERROR (SyncWorker_2) [custom_components.ring] Unable to connect to Ring service: 403 Client Error: Forbidden for url: https://api.ring.com/clients_api/session
2019-12-20 10:25:40 ERROR (MainThread) [homeassistant.setup] Setup failed for ring: Component failed to initialize.
2019-12-20 10:25:40 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of binary_sensor.ring. Setup failed for dependencies: ring
2019-12-20 10:25:40 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform binary_sensor.ring: Could not setup all dependencies.
2019-12-20 10:25:40 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of sensor.ring. Setup failed for dependencies: ring
2019-12-20 10:25:40 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.ring: Could not setup all dependencies.
2019-12-20 10:25:40 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of camera.ring. Setup failed for dependencies: ring
2019-12-20 10:25:40 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform camera.ring: Could not setup all dependencies.`

`[homeassistant@hassio ring]$ ls -la /home/homeassistant/.homeassistant/custom_components/ring/
total 44
drwx------. 3 homeassistant homeassistant 4096 Dec 20 10:25 .
drwxrwxr-x. 7 homeassistant homeassistant   78 Dec 20 10:25 ..
-rw-rw-r--. 1 homeassistant homeassistant 3835 Dec 20 10:25 binary_sensor.py
-rw-rw-r--. 1 homeassistant homeassistant 6195 Dec 20 10:25 camera.py
-rw-rw-r--. 1 homeassistant homeassistant 2933 Dec 20 10:25 __init__.py
-rw-rw-r--. 1 homeassistant homeassistant 2991 Dec 20 10:25 light.py
-rw-rw-r--. 1 homeassistant homeassistant  321 Dec 20 10:25 manifest.json
drwxrwxr-x. 2 homeassistant homeassistant   36 Dec 20 10:25 __pycache__
-rw-rw-r--. 1 homeassistant homeassistant 6712 Dec 20 10:25 sensor.py
-rw-rw-r--. 1 homeassistant homeassistant   73 Dec 20 10:25 services.yaml
-rw-rw-r--. 1 homeassistant homeassistant 3404 Dec 20 10:25 switch.py`

**Comment by jaraeez** [comment] 2019-12-20 00:42
Also removed the _.ring_cache.pickle_ & restarted still same issue.

**Comment by raymondoooo** [comment] 2019-12-20 01:28
@xernaj thanks so much for putting this together!  worked like a charm here!

@Scope666 thanks for the quick and dirty directions!  they were perfect!

**Comment by brama1966** [comment] 2019-12-20 02:03
Yeah i think its better to just update the ring_doorbell library rather than the HA ring component as there isn't an issue with that part of the code

**Comment by jaraeez** [comment] 2019-12-20 02:13
Not sure if this is the best way though I've managed to get it working by unzipping

> https://github.com/xernaj/python-ring-doorbell/archive/fix/oauth-fail-due-to-blocked-user-agent.zip#ring_doorbell==0.2.4

& copying the contents of ring_doorbell to _/srv/homeassistant/lib/python3.6/site-packages/ring_doorbell_ then removing the ring directory in _custom_components_ & restarting HA

**Comment by brama1966** [comment] 2019-12-20 02:24
> 
> 
> Not sure if this is the best way though I've managed to get it working by unzipping
> 
> > https://github.com/xernaj/python-ring-doorbell/archive/fix/oauth-fail-due-to-blocked-user-agent.zip#ring_doorbell==0.2.4
> 
> & copying the contents of ring_doorbell to _/srv/homeassistant/lib/python3.6/site-packages/ring_doorbell_ then removing the ring directory in _custom_components_ & restarting HA

no that completely correct 
it's basically what i did but i took the complete changes that where made by #143 
https://github.com/xernaj/python-ring-doorbell/tree/fix/oauth-fail-due-to-blocked-user-agent
and that worked for me
the GODS are please and that's all that matters
true

**Comment by rpitera** [comment] 2019-12-20 04:34
@xernaj - Thanks mate - copied over your zip file and it works again.  At least this will tide me over until NabuCasa gets a chance to contact Ring about partnering.  Would be better in the long run, assuming that Ring actually responds faster than their cameras/doorbells do.  LOL

**Comment by jaraeez** [comment] 2019-12-20 04:35
Wanted to say that I'm getting a lot of the below

> [homeassistant.components.binary_sensor] Updating ring binary_sensor took longer than the scheduled update interval 0:00:05

Not seen this before & will add scan_interval 300 to the configuration.yaml & see if that stops the log filling up

**Comment by Diondk** [comment] 2019-12-20 05:17
Ok, i got this working again :) Thanks for the quick fix!

**Comment by balloob** [comment] 2019-12-20 09:31
I am in touch with Ring and working on getting an official client ID/secret for Ring. It means that this lib will need to be updated to allow passing in an authentication object. I wrote up an issue for this here: #144

**Comment by markbajaj** [comment] 2019-12-20 09:58
> Not sure if this is the best way though I've managed to get it working by unzipping
> 
> > https://github.com/xernaj/python-ring-doorbell/archive/fix/oauth-fail-due-to-blocked-user-agent.zip#ring_doorbell==0.2.4
> 
> & copying the contents of ring_doorbell to _/srv/homeassistant/lib/python3.6/site-packages/ring_doorbell_ then removing the ring directory in _custom_components_ & restarting HA

Worked perfectly! Thanks

**Comment by biver0** [comment] 2019-12-20 14:12
I'm running hassio on ubuntu and I can't find the  /srv/homeassistant/lib/python3.6/site-packages/ring_doorbell folder.  

I did a find and came up with:

/var/lib/docker/overlay2/2396f6e2e74788192a166858fa22ee5585c542e25bfdc94585d6da6933e39aa4/diff/usr/local/lib/python3.7/site-packages/ring_doorbell
/var/lib/docker/overlay2/97e4edf37a5b80ccb11797ee8d97efbcd745a767594c4759a4a0d2357817063a/diff/usr/local/lib/python3.7/site-packages/
/var/lib/docker/overlay2/017c064616e8bc7ba0d5688793d41444edfe11e0bae8584c8d22491b497dc172/merged/usr/local/lib/python3.7/site-packages/ring_doorbell

Are any of those places the right place to drop these updated files?

**Comment by tuinjie** [comment] 2019-12-20 14:24
@biver0  - same installation and issue?

Any help anyone?

**Comment by raymondoooo** [comment] 2019-12-20 14:36
> @biver0 - same installation and issue?
> 
> Any help anyone?

I have HA in a docker (not hassio).  My package was in -  /usr/local/lib/python3.7/site-packages/ring_doorbell

**Comment by silviudc** [comment] 2019-12-20 14:37
Where can I find the path for Hassio on a pi?

**Comment by biver0** [comment] 2019-12-20 14:46
@raymondoooo  I have a 
/usr/local/lib/python3.6/site-packages folder but it's empty.

**Comment by tuinjie** [comment] 2019-12-20 14:47
@raymondoooo I have same directory but empty

**Comment by ocalvo** [comment] 2019-12-20 14:59
I would not follow this procedure in hassio, in the best case it won't work and in the worst case you could render you installation not serviciable.

**Comment by Scope666** [comment] 2019-12-20 14:59
If you scroll up, I zipped up a custom_component.  One advantage is it should survive a version upgrade.

**Comment by ocalvo** [comment] 2019-12-20 15:00
If you must custom components is the way for hassio

**Comment by biver0** [comment] 2019-12-20 15:09
ok, so unless I'm missing something...

I downloaded the ring folder (from @Scope666 above) and put it in custom components and restarted Hass.  

Nothing changed.  I'm still at 403 error.

I looked in the manifest.json file and it shows:

  "requirements": [
    "https://github.com/xernaj/python-ring-doorbell/archive/fix/oauth-fail-due-to-blocked-user-agent.zip#ring_doorbell==0.2.4"

I'm assuming that's the correct github link?

**Comment by Scope666** [comment] 2019-12-20 15:11
It is, and it's what I did yesterday.  I watched the log while it was
booting and I saw it fetch that component (printed in the log 3 times) and
then finished booting and was working.

**Comment by biver0** [comment] 2019-12-20 15:13
And nothing else changes in my configuration.yaml file?

ring:
  username: !secret ring_username
  password: !secret ring_password

**Comment by biver0** [comment] 2019-12-20 15:14
One thing I've noticed is that the error I get seems to bounce between 403 and 401: 

Error: 401 Client Error: Unauthorized for url: https://api.ring.com/clients_api/session
You will need to restart hass after fixing.

**Comment by Scope666** [comment] 2019-12-20 15:15
No... maybe verify at ring.com by manually logging in that your username / password are good.

**Comment by tuinjie** [comment] 2019-12-20 15:22
@Scope666 followed your instructions copied contents of zip to custom components directory, restarted haasio and working ... hooray!

**Comment by biver0** [comment] 2019-12-20 15:27
@Scope666 Bad password.  I'm so ashamed.  THANK you.

**Comment by tuinjie** [comment] 2019-12-20 15:29
@biver0 happens to us all :-)

**Comment by biver0** [comment] 2019-12-20 15:34
OK, everything is back!  Thank you everyone for your efforts!  

Now if someone could just tell me to get my last recorded video to play back at normal speed rather than 2x.

**Comment by silviudc** [comment] 2019-12-20 15:44
Yup for anyone with Hassio on a raspberry pi, this link from above fixes it: https://drive.google.com/file/d/1C41E7OlOUZLtXBHosV9U6HTlBWNN8Cxf/view?usp=sharing

**Closed** 2019-12-20 16:10 UTC

**Comment by Scope666** [comment] 2019-12-20 16:46
> OK, everything is back! Thank you everyone for your efforts!
> 
> Now if someone could just tell me to get my last recorded video to play back at normal speed rather than 2x.

LOL, mine still do that too... here's the secret, hear the theme from Benny Hill in your head while watching the video and you will be THOROUGHLY entertained.     ;)

**Comment by rpitera** [comment] 2019-12-20 17:16
Mine do it as well; I thought I had just set up something incorrectly.  So I guess that's just how it is then?

**Comment by Scope666** [comment] 2019-12-20 17:25
I think so.  I remember when I first set it up playing with all kinds of ffmpeg parameters but nothing seemed to change the accelerated rate.  Over time I've almost grown to like it because it saves time reviewing clips.

**Comment by GuruPG** [comment] 2019-12-20 19:01
I had same issue. 
Applied the zip file from @Scope666 (many thanks)
Everything is back except the binary.sensor_ring_front_door_ding & binary.sensor_ring_front_door_motion
Any ideas?

**Comment by rrabb** [comment] 2019-12-20 19:04
Thanks everyone for taking care of this issue so fast!!

**Comment by Scope666** [comment] 2019-12-20 19:51
@GuruPG   Try going to your "States" page and see if it shows up there.  Sometimes things get renamed on their own.  (or search through "Entities")

**Comment by GuruPG** [comment] 2019-12-20 20:19
Thanks @Scope666 
Turns out I just hadn’t copied the binary_sensor.py across properly. Deleted it and copied yours across again. All now working perfectly. 
Many thanks.

**Comment by Scope666** [comment] 2019-12-20 20:33
https://github.com/home-assistant/home-assistant/releases/tag/0.103.3

Fix is cooked in so hopefully we can ditch the custom_component / manual hacks.

**Comment by MikeJMcGuire** [comment] 2019-12-21 00:13
Has anyone tried 103.3 with the update? There's been no change for me since upgrading to 103.3.

**Comment by Scope666** [comment] 2019-12-21 00:15
It hasn't been pushed to Hassio yet, once it is I'll test and report back.

**Comment by MikeJMcGuire** [comment] 2019-12-21 00:16
Ah, thanks mate.

**Comment by jaburges** [comment] 2019-12-21 00:17
> https://github.com/home-assistant/home-assistant/releases/tag/0.103.3
> 
> Fix is cooked in so hopefully we can ditch the custom_component / manual hacks.

Damn I love this community! by the time I found some time to implement a fix, an updated docker was already ready :) Thanks to everyone who resolved!

**Comment by disenberg** [comment] 2019-12-21 01:20
Yes.  103.3 for hassio fixed it.  After turning off 2fa.

**Comment by Scope666** [comment] 2019-12-21 06:34
Same here, deleted custom_component, upgraded and all is back to normal with Ring.  ( v0.103.3 )

**Comment by broyuken** [comment] 2019-12-21 12:33
Does 2FA work with it? I’d like to turn it on if possible.

**Comment by d0ugal** [comment] 2019-12-21 13:55
@broyuken no, 2FA doesn’t work with it. I had to disable.

**Comment by xernaj** [comment] 2019-12-21 21:16
You could enable 2FA on your main login then share cameras with a second email account and use the secondary account with no 2FA for HA.

**Comment by GuruPG** [comment] 2019-12-24 21:45
Seems to have gone down again.

**Comment by raymondoooo** [comment] 2019-12-25 02:42
Yep.  Down for me as well.  Haven’t had too much time to dig into it...

**Comment by austwhite** [comment] 2019-12-25 02:43
This was a very temporary fix.  Seems we are blocked by Ring again.

**Comment by mynameisgv** [comment] 2019-12-28 18:44
It does not work with 0.103.4 with or without 2FA.

**Comment by albertcard** [comment] 2019-12-29 00:45
> It does not work with 0.103.4 with or without 2FA.

@mynameisgv , I upgraded to '**homeassistant==0.103.5**' (which also upgrades **ring-doorbell** to version **0.2.8**) and it looks to have resolved the problem for now. However, Homeassistant now makes so many queries per second to **oauth.ring.com**.

**Comment by tchellomello** [comment] 2019-12-29 04:34
@albertcard  Thanks for your report. There is an issue opened for the number of DNS queries at  #160

**Comment by HemiBob** [comment] 2020-01-10 01:04
> OK, everything is back! Thank you everyone for your efforts!
> 
> Now if someone could just tell me to get my last recorded video to play back at normal speed rather than 2x.

Mine used to play at half speed, until it stopped altogether today

**Comment by Tosko4** [comment] 2020-01-10 17:19
@HemiBob I have the same. It stopped working again yesterday afternoon for me (GMT +2 timezone here)
