### ISSUE TITLE
get_snapshot() yields error 401

### ISSUE THREAD

**Issue by budachst** [tchellomello/python-ring-doorbell#124] opened 2019-03-17 21:26 UTC
I am tryingt to get a snapshot from my ring video pro, by calling get_snapshot() for that object. However, all I am getting is the following error:

`ERROR - Unexpected error:401 Client Error: Unauthorized for url: https://api.ring.com/clients_api/session`

My code, where I am trying to grab the snapshot looks like this:

`def getDeviceInfo(dev):
    dev.update()
    devSnap=dev.get_snapshot()
    logger.info("Updating device data for device '"+dev.name+"' in FHEM...")
    srRing('account ' + str(dev.account_id), dev)
    srRing('address ' + str(dev.address), dev)
    srRing('family ' + str(dev.family), dev)
    srRing('id ' + str(dev.id), dev)
    srRing('name ' + str(dev.name), dev)
    srRing('timezone ' + str(dev.timezone), dev)
    srRing('doorbellType ' + str(dev.existing_doorbell_type), dev)
    srRing('battery ' + str(dev.battery_life), dev)
    srRing('ringVolume ' + str(dev.volume), dev)
    srRing('connectionStatus ' + str(dev.connection_status), dev)
    srRing('WifiName ' + str(dev.wifi_name), dev)
    srRing('WifiRSSI ' + str(dev.wifi_signal_strength), dev)`

So, the function dev.update() works, but dev.get_snapshot() not. The rest of the function just retrieves some attributes, which are then send to another process in the system.

**Comment by dshokouhi** [comment] 2019-03-25 19:47
Seeing the same 401 error here too.

**Comment by rborgwald** [comment] 2019-04-03 00:55
Same issue for me - does anyone know of a workaround?

**Comment by dgreif** [comment] 2019-06-18 23:28
I'm doing some snapshot investigation for my [homebridge plugin](https://github.com/dgreif/ring-alarm/tree/master/homebridge) and noticed you might have an issue on this line: https://github.com/tchellomello/python-ring-doorbell/blob/7ab56fcd7d0b600c4fb5f3e25e4eef974bd71d2d/ring_doorbell/doorbot.py#L378

This is hitting the `snapshots/timestamp` endpoint with a `GET`, which returns a `405` with body `expected method POST`.  I'm not sure how that's leading to a `401` to external users, but I suggest you update that line to match this one:

https://github.com/tchellomello/python-ring-doorbell/blob/7ab56fcd7d0b600c4fb5f3e25e4eef974bd71d2d/ring_doorbell/doorbot.py#L382-L383

Another step that I am taking in my implementation is to grab the `response["timestamps"][0]["timestamp"]` from the _first_ request and using that as the compare value, rather than `time.time()` which can differ by machine if their clock is off.

**Comment by problemss** [comment] 2019-06-25 19:06
@dgreif is changing it to a post fixing it for you?

**Comment by dgreif** [comment] 2019-06-25 19:09
@problemss I haven't actually tried the change with the python library (I live in nodejs land), but I would think this line would cause issues based on the defaults for `self._ring.query`.  I'd recommend someone try it out and see if it fixes the issue

**Comment by problemss** [comment] 2019-06-25 19:53
@dgreif Does the snapshot work in your home bridge plugin?

**Comment by dgreif** [comment] 2019-06-25 19:56
Yep, it's working great.  I looked at the python library while i was figuring out how to do it and happened to notice the discrepancies in the way the `timestamp` endpoint is being called.

**Comment by problemss** [comment] 2019-06-25 19:59
@dgreif Thank you for your help with this project and i will have to try out your plugin for my homebridge implementation!

**Comment by dgreif** [comment] 2019-06-25 20:13
No problem @problemss!  Hope the homebridge plugin suites your needs 😄. Here are the pertinent lines from my node api: https://github.com/dgreif/ring-alarm/blob/944b04d528a53e1b908ec68a022390fd4261bd23/api/ring-camera.ts#L160-L217 .  I actually beefed it up a bit this morning because the older versions of the doorbell apparently only update the snapshot every 10 minutes, not on-demand like newer versions.

As for the `401` issue, I'm second-guessing my assessment (although I do think those lines still need updating).  Looks like the `401` is from the `clients_api/session` endpoint.  A `401` there means your auth token is invalid.  This sounds like an issue with the auth code in general, not with snapshots specifically.  Do other methods work for users who are getting `401`s for snapshots?

**Comment by odenisenko** [comment] 2019-06-27 23:09
team.
as I can see @tchellomello use old auth method.
now we shouldn't use any auth_token (in url query) and we should use simple and standard oAuth auth.
so. I write a simple application and it works like a charm.

```
#!/usr/bin/python
# -*- coding: utf-8 -*-.
# by tender

import os
import json
from datetime import datetime
import time
import requests

ring_email = "Bill.Gates@gmail.com"
ring_password = "Micro$oft"

TOKEN_PATH = os.path.join(
    "./", 
    'ring.oauth'
)

def get_ring_token(email, password):
    token = None

    if os.path.isfile(TOKEN_PATH):
       with open(TOKEN_PATH, 'r') as infile:
            token = json.load(infile)

    if not token:
       url = "https://oauth.ring.com/oauth/token"
       payload = { "client_id": 'ring_official_android', "grant_type": 'password', "password": password, "username": email, "scope": 'client' }
       r = requests.post(url, data=json.dumps(payload))
       token = r.json()
       with open(TOKEN_PATH, 'w') as outfile:
            json.dump(token, outfile)
    else:
       token_age = time.time() - os.path.getmtime(TOKEN_PATH)
       if token_age >= token["expires_in"]:
          print(token_age)
          print(token["expires_in"])
          print("OLD!")
       else:
          pass

    return token

token = get_ring_token(ring_email, ring_password)
headers = {'user-agent': 'android:com.ringapp:2.0.67(423)', "Authorization": "Bearer %s" %token["access_token"]}

url = "https://api.ring.com/clients_api/" + "ring_devices"
r = requests.get(url, headers=headers)
response = r.json()
device_id = (response["doorbots"][0]["id"])

url = "https://api.ring.com/clients_api/" + "snapshots/timestamps"
json = {"doorbot_ids": [device_id]}
r = requests.post(url, headers=headers, json=json)
response = r.json()
timestamp = response["timestamps"][0]["timestamp"]
print(timestamp)

time.sleep(5)

url = "https://api.ring.com/clients_api/" + "snapshots/image/" + str(device_id)
r = requests.get(url, headers=headers)
open('snapshot.jpg', 'wb').write(r.content)
```
![image](https://user-images.githubusercontent.com/44768566/60306663-b92e6a80-9949-11e9-8a6a-1a4507542b9d.png)

**Comment by dgreif** [comment] 2019-06-27 23:19
I can confirm that this is the issue with the `timestamp` endpoint.  I was running into other issues in my homebridge plugin because I was _only_ using oauth (Authorization: Bearer token) with all the endpoints.  When I tried using the session `auth_token` in the query string for all api requests, I received 401s for _just_ the timestamps endpoint.  My recommendation is to use the authorization header for _all_ endpoints _except_ `dings/active`, `vod` and `ring_devices`.  These endpoints work together with `session` to give you unique active dings for each session.  It's taken a lot of tinkering to figure this out, but I'm happy to give more detail if you need it.  I would also still recommend making the code changes I have previously mentioned (referring to `self._ring.query(url, json=payload)`), as the `timestamp` endpoint won't accept a `GET`.

**Comment by odenisenko** [comment] 2019-06-28 06:01
@dgreif hi!
>dings/active, vod and ring_devices. These endpoints work together with session to give you unique active dings for each session. 

it's not clear for me, sorry.
1) I have traced my ring traffic with my drytek vigor 2925 and can't find any calling with "auth_token" in query param. 
at all
2) these endpoints working without "auth_token" query param - OK.
so, can you clarify what you mean?

thnx!

**Comment by odenisenko** [comment] 2019-06-28 08:33
bonus

```python

from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw 

                img = Image.open(WEB_PATH + 'snapshot.jpg')
                ImageDraw.Draw(
                    img  # Image
                ).text(
                    (0, 0),  # Coordinates
                    '{}'.format(datetime.datetime.now().strftime("%m/%d/%Y, %H:%M:%S")),
                    (255, 0, 0)  # Color
                )
                img.save(WEB_PATH + 'snapshot.jpg')

```

**Comment by dgreif** [comment] 2019-06-28 16:00
@odenisenko The biggest issue that I have run into using _just_ oauth is that calling the `dings/active` endpoint leads to weird results.  If you have 2 clients polling the endpoint, sometimes only 1 or neither client will see a ding.  It's as if the dings are in a shared pool, and the first client to request active dings will see it, but no one else gets to see it.  The current session auth approach in this library (and other libraries) does not seem to have that issue, which is why I was looking into session auth to fix my issues.  If Ring is no longer using the session for auth based on your tracing, then there must be another mechanism (like the `hardware_id` header) that they are using to determine which dings you have seen so far.  I'll do more testing over the next few days and let you know when I have conclusive results

**Comment by odenisenko** [comment] 2019-06-28 16:25
@dgreif thank you for your answer.
Have a nice day!

**Comment by dgreif** [comment] 2019-06-28 18:18
@odenisenko this was really bugging me so I dove and and did a bunch of testing to confirm my theories.  It is indeed the `hardware_id` that tells `dings/active` which pool of events you should be pulling from.  Here is the bare minimum auth sequence to get reliable data:

1. Get an `access_token` from `https://oauth.ring.com/oauth/token`
2. Create a session using `access_token` in `Authorization` header at `https://api.ring.com/clients_api/session` with a unique `hardware_id` in the body.  Keep track of this `hardware_id`, but the rest of the session data is now pointless
3. For all requests (`dings/active`, `snapshots/timestamp`, etc), include  `hardware_id: '${hardware id for this session}'` and `Authorization: 'Bearer ${access_token}'` headers.  This uses oauth to authenticate your access, and session `hardware_id` to know which dings and other data belong to this unique session.

I will be pushing an update to my node library in the coming days once I get a chance to cover corner cases like when a session or auth token expire.  Hopefully this info is helpful for someone with python experience to update this library and get snapshots up and working again.  Let me know if you need more info!

**Comment by galadril** [comment] 2019-08-02 11:53
Do you need the paid subscribtion for the get_snaphot to work?

**Comment by isabellaalstrom** [comment] 2019-08-02 12:06
@odenisenko Hi! I'm trying to use the code you contributed above to get my snapshot, but I get a 404 on the request for the snapshot, and response "no snapshot". Have any idea why? I have a Ring doorbell 2.

**Comment by tchellomello** [comment] 2019-08-02 15:05
Hello guys, I'll take a look this weekend on this issue.

**Comment by odenisenko** [comment] 2019-08-10 15:43
> Do you need the paid subscribtion for the get_snaphot to work?

no

**Comment by clement-chung** [comment] 2019-08-22 05:12
Hi @tchellomello , any chance to get the fix merged into master and close the issue?

Thanks.

**Comment by zhenqidong** [comment] 2019-09-27 03:26
> team.
> as I can see @tchellomello use old auth method.
> now we shouldn't use any auth_token (in url query) and we should use simple and standard oAuth auth.
> so. I have write a simple application and it works like a charm.
> 
> ```python
> #!/usr/bin/python
> # -*- coding: utf-8 -*-.
> # by tender
> 
> import os
> import json
> from datetime import datetime
> import time
> import requests
> 
> ring_email = "Bill.Gates@gmail.com"
> ring_password = "Micro$oft"
> 
> TOKEN_PATH = os.path.join(
>     "./", 
>     'ring.oauth'
> )
> 
> def refresh_ring_token(refresh_token):
>     payload = { "client_id": 'ring_official_android', "grant_type": 'refresh_token', "refresh_token": refresh_token }
>     url = "https://oauth.ring.com/oauth/token"
>     r = requests.post(url, data=json.dumps(payload))
>     if r.ok:
>             return r.json()
>     else:
>             return None
> 
> def get_ring_token(email, password):
>     token = None
> 
>     if os.path.isfile(TOKEN_PATH):
>        with open(TOKEN_PATH, 'r') as infile:
>             token = json.load(infile)
> 
>     if not token:
>        url = "https://oauth.ring.com/oauth/token"
>        payload = { "client_id": 'ring_official_android', "grant_type": 'password', "password": password, "username": email, "scope": 'client' }
>        r = requests.post(url, data=json.dumps(payload))
>        if r.ok:
>           token = r.json()
>           with open(TOKEN_PATH, 'w') as outfile:
>              json.dump(token, outfile)
>        else:
>           return None
>     else:
>        token_age = time.time() - os.path.getmtime(TOKEN_PATH)
>        if token_age >= token["expires_in"]:
>           token = refresh_ring_token(token["refresh_token"])
>           if not token:
>              return None
>           else:
>              with open(TOKEN_PATH, 'w') as outfile:
>                 json.dump(token, outfile)
> 
>     return token
> 
> token = get_ring_token(ring_email, ring_password)
> headers = {'user-agent': 'android:com.ringapp:2.0.67(423)', "Authorization": "Bearer %s" %token["access_token"]}
> 
> url = "https://api.ring.com/clients_api/" + "ring_devices"
> r = requests.get(url, headers=headers)
> response = r.json()
> device_id = (response["doorbots"][0]["id"])
> #print(device_id)
> 
> #url = "https://api.ring.com/clients_api/" + "doorbots/history?limit=5"
> #r = requests.get(url, headers=headers)
> #response = r.json()
> #print(response)
> 
> #url = "https://api.ring.com/clients_api/" + "snapshots/timestamps"
> #json = {"doorbot_ids": [device_id]}
> #r = requests.post(url, headers=headers, json=json)
> #response = r.json()
> #timestamp = response["timestamps"][0]["timestamp"]
> #print(timestamp)
> #time.sleep(5)
> 
> url = "https://api.ring.com/clients_api/" + "snapshots/image/" + str(device_id)
> r = requests.get(url, headers=headers)
> open('snapshot.jpg', 'wb').write(r.content)
> ```
> 
> ![image](https://user-images.githubusercontent.com/44768566/60306663-b92e6a80-9949-11e9-8a6a-1a4507542b9d.png)

@dgreif, I confirmed your theory, it seems snapshot API only takes access_token in Authorization header for authentication, not the auth_token in URL params.
Also what I've found is that Ring only keeps one snapshot at a given time, have you found out how often Ring generates the snapshot?

Thanks,

**Comment by dgreif** [comment] 2019-10-01 13:22
Ring only updates the snapshot when you send a POST to `https://api.ring.com/clients_api/snapshots/timestamps`.  If you post the desired camera id in `doorbot_ids`, then the camera will respond by posting a new snapshot and updating the timestamp on the `timestamps` endpoint.  Wired cameras can only post snapshots every 30 seconds, while battery cameras are limited to one snapshot per 10 minutes.  The server only keeps the latest image for each camera on hand.

**Comment by tchellomello** [comment] 2020-01-06 19:23
> Hi @tchellomello , any chance to get the fix merged into master and close the issue?
> 
> Thanks.

Hello @clement-chung  I would be happy to merge a PR to implement this.

**Closed** 2020-11-26 19:39 UTC

**Comment by Kaiserben** [comment] 2022-12-20 12:54
> > Do you need the paid subscribtion for the get_snaphot to work?
> 
> no

Is is still the case? I tried to fetch a snapshot from Ring and get the response : "No Snapshot". The camera is well available and I can get a video from HomeKit or Ring app without any issue.

**Comment by 4Dolio** [comment] 2022-12-20 21:22
I'm simply commenting here because I want to follow up later and add the download of the snapshot frames videos as presented in the ring app via my video archival process that uses this api...
